"""Convert to JSON

Revision ID: 569934902f9d
Revises: cbe1d38fed8a
Create Date: 2022-11-23 12:06:28.675294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569934902f9d'
down_revision = 'cbe1d38fed8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
